### PR TITLE
add CS131

### PR DESCRIPTION
**Pull request by victoryang00**

### CODE REVIEW

**Comment by why-in-Shanghaitech** [comment]
Thank you for your contribution. It seems that you've done a lot on my project!

Unfortunately, there are several boilers in your commit:
1. People images should only end with '.jpg';
2. When you want to show new people in semesters, you should first add them to the people database (people/meta.json). Otherwise, they won't show up. (for each person, 'name' is required, others are optional)

Since I am developing a simple UI for metadata management, you have 2 choices:
1. Fix this up based on your current commit. I'll merge this pull request once you've done that;
2. Wait for me to finish up my UI system. Things might be easier, but you have to wait for several weeks (hopefully).

**Comment by victoryang00** [comment]
By the way, grabbing img from oa.shanghaitech.edu.cn is too ugly for me, so my policy is to make my img better than that.

**Comment by victoryang00** [comment]
Will conrinuosly push CS224 Software Analysis and CS225 Distributed System after guaduation.

**Comment by why-in-Shanghaitech** [comment]
It seems that you haven't finished yet? 

Some problems:
1. Several images and people ids are wrong (sp17).
2. Please use lower-case letters as people id.
3. Do not introduce dummy files (I notice that you add `yangyw.png` without using it). 
4. Use your own image instead of an avatar.
5. It has caused conflicts since I'm maintaining CS274A this semester.

I think it is not easy for you to do 2, 3 since they can't get fixed in the browser by now. Some choices:
1. Fix 1-4 and I'll resolve the conflict;
2. Destroy the repo and fork again;
3. Ask me to fix the problems for you. I should be able to add commits to your branch now. If you choose this, fix 1 first since I don't know the names of the TAs.

**Comment by why-in-Shanghaitech** [comment]
I manually merged this branch... I'll close this pull request. Thank you for your contribution.

**Pull request closed without merging**
