### PR TITLE
addition of SI100B Fall2022

### PR DESCRIPTION
**Pull request by itsuitsuki**

### CODE REVIEW

**Comment by why-in-Shanghaitech** [comment]
Thank you very much for your contribution! I may look into it in a couple of days.

**Comment by why-in-Shanghaitech** [comment]
Hi! I've noticed that you left the grading criteria section blank. According to the 1st slide, I think it might be okay to inherit from the previous semester. What do you think? I'm not sure whether the grading criteria changed during the semester.

**Comment by itsuitsuki** [comment]
> Hi! I've noticed that you left the grading criteria section blank. According to the 1st slide, I think it might be okay to inherit from the previous semester. What do you think? I'm not sure whether the grading criteria changed during the semester.

I think inheritance is feasible, but I failed to find substantial evidence of this inheritance in lecture materials, until you noticed me that it's in the 1st slide. If the inheritance is a must, we can initially merge the PR and I can hold a new PR about grading criteria, because I found that my personal space was empty due to bug or something so that I probably have to re-initialize it again if I close this PR to add new commits.

**Comment by why-in-Shanghaitech** [comment]
Thank you for your reply! I made an additional commit to your branch. Now everything looks fine.

**Review by why-in-Shanghaitech — APPROVED** [review]
LGTM

**Comment by why-in-Shanghaitech** [comment]
Again, thanks very much for your contribution! iTechX could help more students because of you.

**Pull request merged**
