### PR TITLE
Add some contents in CS274A 2024 Spring, add course BME2104

### PR DESCRIPTION
**Pull request by kichiok**
Add Homework Solutions and Lecture Slides.

### CODE REVIEW

**Comment by why-in-Shanghaitech** [comment]
Hi! Thank you very much for your contribution! I'll review this PR in a few days.
I've noticed that this is your first contribution. I'll add you to the contributor list once the pull request is accepted.

**Comment by kciok** [comment]
I also add BME2104 to the repo.

Grateful to this repo. Hope my contribution could play a helpful role. Looking forward to your reply.

**Comment by kciok** [comment]
> I also add BME2104 to the repo.
> 
> Grateful to this repo. Hope my contribution could play a helpful role. Looking forward to your reply.

I commit BME2104 after I submit this PR. should i submit a new PR?

sorry for not being proficient in using Git.

**Comment by why-in-Shanghaitech** [comment]
Thank you for your dedicated contributions! There's no need to make a new PR, a modification to the title of this PR is enough.

**Review by why-in-Shanghaitech — APPROVED** [review]
LGTM

**Comment by why-in-Shanghaitech** [comment]
Again, thank you for your great contribution! I have added you to the iTechX contributor list.

**Pull request merged**
